// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIFvBXYyCM5ilLWC1NSoQsmoDWkRqtVbc',
    appId: '1:1040324003218:web:a74fd5dc628fe44517ad4b',
    messagingSenderId: '1040324003218',
    projectId: 'chatapp-6bdb2',
    authDomain: 'chatapp-6bdb2.firebaseapp.com',
    storageBucket: 'chatapp-6bdb2.appspot.com',
    measurementId: 'G-8FQJKCHX5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFx_j1Udq8Qwv8U3Be_UCiBt_As6JCxxM',
    appId: '1:1040324003218:android:3fdde154d2077adc17ad4b',
    messagingSenderId: '1040324003218',
    projectId: 'chatapp-6bdb2',
    storageBucket: 'chatapp-6bdb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3MHalGaQbWJaJsetmwyBkQpqjs9prVqo',
    appId: '1:1040324003218:ios:8e24b43f382640d317ad4b',
    messagingSenderId: '1040324003218',
    projectId: 'chatapp-6bdb2',
    storageBucket: 'chatapp-6bdb2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3MHalGaQbWJaJsetmwyBkQpqjs9prVqo',
    appId: '1:1040324003218:ios:cb674f8f01045e5e17ad4b',
    messagingSenderId: '1040324003218',
    projectId: 'chatapp-6bdb2',
    storageBucket: 'chatapp-6bdb2.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
